server:
  port: 8080
  servlet:
    context-path: /video # 应用名 localhost:8090/auth

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://43.128.46.139:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,页面会显示主机名
    preferIpAddress: true     #访问路径可以显示IP地址
    ip-address: 119.28.87.104

spring:
  jackson:


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: video-server # Eureka页面显示
  # 数据源配置
  datasource:
    username: root
    password: s09115/.
    url: jdbc:mysql://43.132.193.154:3306/bibiliTV?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    #mysql8版本以上驱动包指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    #   数据源其他配置, 在 DruidConfig配置类中手动绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL

mybatis-plus:
  # 指定实体类所有包
  type-aliases-package: cn.leolam.www.video.web.entities

# 日志级别，会打印sql语句
logging:
  level:
    cn.leolam.www.video.web.mapper: debug

video:
  tokenString: leolam
  pageSizeOnHomePage: 10
  gateWayUrl: http://43.128.46.139:7001
  lunBoPic: 5
  pageSizeOnSearchPage: 10
  pageSizeOnCollectionPage: 10
  pageSizeOnDetailPage: 6
  emailAddress: 1124013284@qq.com
  emailPassWord: hnqwzcsbvbdnjggd